clean:
	cd fsharp/cli         && dotnet clean && rm -rf bin && rm -rf obj
	cd fsharp/hello-world && dotnet clean && rm -rf bin && rm -rf obj
	cd csharp/cli         && dotnet clean && rm -rf bin && rm -rf obj
	cd csharp/hello-world && dotnet clean && rm -rf bin && rm -rf obj
	cd vb/cli             && dotnet clean && rm -rf bin && rm -rf obj
	cd vb/hello-world     && dotnet clean && rm -rf bin && rm -rf obj
