name: debug

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    permissions:
      packages: write

    steps:

    - name: Set up .NET
      uses: actions/setup-dotnet@v4

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install fantomas
      run: |
        dotnet tool install fantomas

    - name: Package artifacts
      run: |
        dotnet --version
        make release
        $file = Get-ChildItem -Path ./uhppoted/uhppoted/dist -Filter *.nupkg | Select-Object -ExpandProperty Name
        echo ">>>>>>>>>>>>>>>> $file"
        $filepath = Join-Path -Path ./uhppoted/uhppoted/dist -ChildPath $file
        echo ">>>>>>>>>>>>>>>> $filepath"
        echo "NUPKG=$filepath" >> $env:GITHUB_ENV

    - name: Publish to NuGet
      run: |
        echo ">>>>>>>>>>>>>>>> $"$env:NUPKG"
   