name: examples

on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    strategy:
      matrix:
        version: ['8.x', '9.x']
        framework: ['net8.0', 'net9.0']
    runs-on: windows-latest
    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.version }}

    - name: Check out code
      uses: actions/checkout@v4

    - name: Add Github Packages NuGet registry
      run: |
        dotnet nuget add source --username uhppoted --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/uhppoted/index.json"

    - name: Build hello-world F# example
      run: |
        cd examples/fsharp/hello-world
        dotnet add package uhppoted --version 0.8.9.9-beta
        dotnet build --framework=${{ matrix.framework }}
        dotnet run   --framework=${{ matrix.framework }}

    - name: Build hello-world C# example
      run: |
        cd examples/csharp/hello-world
        dotnet add package uhppoted --version 0.8.9.9-beta
        dotnet build --framework=${{ matrix.framework }}
        dotnet run   --framework=${{ matrix.framework }}

    - name: Build hello-world VB.NET example
      run: |
        cd examples/vb/hello-world
        dotnet add package uhppoted --version 0.8.9.9-beta
        dotnet build --framework=${{ matrix.framework }}
        dotnet run   --framework=${{ matrix.framework }}
