name: release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    permissions:
      packages: write

    steps:

    - name: Set up .NET
      uses: actions/setup-dotnet@v4

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install fantomas
      run: |
        dotnet tool install fantomas

    - name: Package artifacts
      run: |
        dotnet --version
        make release
        dir uhppoted/uhppoted/dist/*.nupkg
        $file = Get-ChildItem -Path ./uhppoted/uhppoted/dist -Filter *.nupkg | Select-Object -ExpandProperty Name
        $filepath = Join-Path -Path ./uhppoted/uhppoted/dist -ChildPath $file
        echo "NUPKG=$filepath" >> $env:GITHUB_ENV

    - name: Publish to Github Packages
      run: |
        echo ">>>> $env:NUPKG"
        # dotnet nuget add source --username uhppoted --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/uhppoted/index.json"
        # dotnet nuget push "$env:NUPKG" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --no-symbols --skip-duplicate 

    - name: Publish to NuGet
      run: |
        echo ">>>> $env:NUPKG"
        # dotnet nuget push "$env:NUPKG" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
