name: release

on:
  workflow_dispatch:
# release:
#   types: [published]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    permissions:
      packages: write

    steps:

    - name: Set up .NET
      uses: actions/setup-dotnet@v4

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install fantomas
      run: |
        dotnet tool install fantomas

    - name: Build
      run: |
        dotnet --version
        make build-all
        make integration-tests

    - name: Package artifacts
      run: |
        make release

    - name: Publish artifacts
      run: |
        dir ./uhppoted/uhppoted/dist
        echo ">>>> list sources (before)"
        dotnet nuget list source
        echo ">>>> try to authenticate"
        dotnet nuget add source --username uhppoted --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/uhppoted/index.json"
        echo ">>>> authenticated presumably"
        dotnet nuget list source
        echo ">>>> 'k, time to push'"
        dotnet nuget push ./uhppoted/uhppoted/dist/uhppoted-test.0.8.9.2-alpha.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
        echo ">>>> pushed apparently but who actually knows"
        dotnet list package
