name: release

on:
  workflow_dispatch:
# release:
#   types: [published]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up .NET
      uses: actions/setup-dotnet@v4

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install fantomas
      run: |
        dotnet tool install fantomas

    - name: Build
      run: |
        dotnet --version
        make build-all
        make integration-tests

    - name: Package artifacts
      run: |
        make release

    - name: Publish artifacts
      run: |
        ls -la ./uhppoted/uhppoted/dist
