name: release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    permissions:
      packages: write

    steps:

    - name: Set up .NET
      uses: actions/setup-dotnet@v4

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install fantomas
      run: |
        dotnet tool install fantomas

    - name: Package artifacts
      run: |
        dotnet --version
        make release
        dir uhppoted/uhppoted/dist/*.nupkg
        $file = Get-ChildItem -Path ./uhppoted/uhppoted/dist -Filter *.nupkg | Select-Object -ExpandProperty Name
        $filepath = Join-Path -Path ./uhppoted/uhppoted/dist -ChildPath $file
        echo "NUPKG=$filepath" >> $env:GITHUB_ENV

    - name: Inspect package (without unzipping)
      run: |
        $zipfile = "$env:NUPKG"
        $filename = "uhppoted.nuspec"
        $zip = [System.IO.Compression.ZipFile]::OpenRead($zipfile)
        $entry = $zip.Entries | Where-Object { $_.FullName -eq $filename }
        if ($entry) {
           $reader = New-Object System.IO.StreamReader($entry.Open())
           Write-Host $reader.ReadToEnd()
        } else {
           Write-Host "File not found"
        }        

    - name: unzip it anyway
      run: |
        cd dist
        unzip uhppoted.0.8.9.5-beta.nupkg
        tree /f /a


    # - name: Publish to Github Packages
    #   run: |
    #     dotnet nuget add source --username uhppoted --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/uhppoted/index.json"
    #     dotnet nuget push "$env:NUPKG" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --no-symbols --skip-duplicate 

    # - name: Publish to NuGet
    #   run: |
    #     dotnet nuget push "$env:NUPKG" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
